In [4]:
import numpy as np

a = [25,34,"Hello"]
a
type(a)

a1 = np.array([23,55,"hi"])
a1

array(['23', '55', 'hi'], dtype='<U11')

In [6]:
m_list_1 = np.array([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])

m_list_1

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0, 6, 7)

array([0., 1., 2., 3., 4., 5., 6.])

In [22]:
np.zeros(5)
# np.array([0,0,0,0,0])

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
m_list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Create NumPy multidimensional (2 axis) array without defining type
np_m_arr_1 = np.array(m_list_1)

np_m_arr_1.size

9

In [32]:
list_1 = [1, 2, 3, 4, 5,45,677]
np_arr_1 = np.array(list_1, dtype=np.int64)
np_arr_1

array([  1,   2,   3,   4,   5,  45, 677], dtype=int64)

In [45]:
from numpy import random
np.random.randint(10, 100, 7)

array([42, 75, 93, 81, 66, 80, 37])

array([   25, 32769,    38])