In [2]:
import numpy as np

a = [25,34,"Hello"]
a
type(a)

a1 = np.array([23,55,"hi"])
a1

array(['23', '55', 'hi'], dtype='<U11')

In [3]:
m_list_1 = np.array([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])

m_list_1

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.linspace(0, 6, 7)

array([0., 1., 2., 3., 4., 5., 6.])

In [6]:
np.zeros(5)
# np.array([0,0,0,0,0])

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
m_list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Create NumPy multidimensional (2 axis) array without defining type
np_m_arr_1 = np.array(m_list_1)

np_m_arr_1.size

9

In [10]:
list_1 = [1, 2, 3, 4, 5,45,677]
np_arr_1 = np.array(list_1, dtype=np.int64)
np_arr_1

array([  1,   2,   3,   4,   5,  45, 677], dtype=int64)

In [11]:
from numpy import random
np.random.randint(10, 100, 7)

array([80, 19, 92, 39, 52, 76, 88])

In [19]:

np.random.randint(10, 50, size=(5, 5))

array([[42, 31, 18, 38, 26],
       [14, 22, 48, 29, 15],
       [10, 32, 44, 47, 45],
       [18, 41, 33, 48, 14],
       [21, 46, 27, 42, 18]])

In [31]:
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np_m_arr_1.shape

(3, 3)

In [27]:
np_m_arr_1[1,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [30]:
np.take(np_m_arr_1, [0, 4, 8])

array([1, 5, 9])

In [40]:
np.put(np_m_arr_1, [0, 4, 8], [10, 10, 10])
np_m_arr_1

array([[10,  2,  3],
       [ 4, 10,  6],
       [ 7,  8, 10]])

In [37]:
np_arr_1[:5:2]

array([1, 3, 5], dtype=int64)

In [42]:
np_m_arr_1[:,0]

array([10,  4,  7])

In [43]:
np_arr_1[::-1]

array([677,  45,   5,   4,   3,   2,   1], dtype=int64)

In [44]:
evens = np_m_arr_1[np_m_arr_1%2==0]
evens

array([10,  2,  4, 10,  6,  8, 10])

In [46]:
arr1 = np.array([[2,4],
                 [6,8]])
arr2 = np.array([[8,5],[3,7]])

np.dot(arr1,arr2)

array([[28, 38],
       [72, 86]])