In [3]:
import numpy as np
x = ["hello",1,"hi",2]
y = np.array(x,dtype=np.str_)
y


array(['hello', '1', 'hi', '2'], dtype='<U5')

In [4]:
m_list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9],[10,11,12]]
m_list_1

np_m_arr_1 = np.array(m_list_1)
print(type(np_m_arr_1))

<class 'numpy.ndarray'>


In [5]:
np.arange(1, 10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np_m_arr_1.size


12

In [9]:
from numpy import random

np.random.randint(10, 50, size=(2, 3))

array([[26, 40, 13],
       [10, 13, 25]])

In [10]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [12]:
np_m_arr_1.shape

(4, 3)

In [13]:
np.take(np_m_arr_1, [0, 3, 6,9])

array([ 1,  4,  7, 10])

In [14]:
np.put(np_m_arr_1, [0, 3, 6, 9], [10, 10, 10, 10])
print(np_m_arr_1)

[[10  2  3]
 [10  5  6]
 [10  8  9]
 [10 11 12]]


In [15]:
list_1 = [1, 2, 3, 4, 5]
np_arr_1 = np.array(list_1, dtype=np.int8)
np_arr_1

np_arr_1[:5:2]

array([1, 3, 5], dtype=int8)

In [16]:
np_m_arr_1[:,2]

array([ 3,  6,  9, 12])

In [17]:
np.unique(np_m_arr_1)

array([ 2,  3,  5,  6,  8,  9, 10, 11, 12])

In [18]:
np_m_arr_1.resize((3,4))
np_m_arr_1

array([[10,  2,  3, 10],
       [ 5,  6, 10,  8],
       [ 9, 10, 11, 12]])

In [19]:
np_m_arr_1.resize((3,4))
np_m_arr_1

array([[10,  2,  3, 10],
       [ 5,  6, 10,  8],
       [ 9, 10, 11, 12]])

In [20]:
np_m_arr_1.transpose()

array([[10,  5,  9],
       [ 2,  6, 10],
       [ 3, 10, 11],
       [10,  8, 12]])

In [21]:
np_m_arr_1.swapaxes(0,1)


array([[10,  5,  9],
       [ 2,  6, 10],
       [ 3, 10, 11],
       [10,  8, 12]])

In [22]:
np_m_arr_1.flatten('F')

array([10,  5,  9,  2,  6, 10,  3, 10, 11, 10,  8, 12])

In [23]:
np_m_arr_1.flatten()

array([10,  2,  3, 10,  5,  6, 10,  8,  9, 10, 11, 12])

In [24]:
arr_3 = np.array([1, 2, 3, 4])
arr_4 = np.array([2, 4, 6, 8])
arr_3 + arr_4

array([ 3,  6,  9, 12])

In [25]:
arr_5 = random.randint(100, size=(4))
arr_5

array([22, 38, 18, 62])

In [26]:
random.choice(arr_3)

1

In [27]:
arr_6 = random.randint(100, size=(2, 3))
arr_6


array([[62, 73, 27],
       [74, 69, 16]])

In [28]:
np.add(arr_3, arr_4)

array([ 3,  6,  9, 12])

In [29]:
arr_5 = np.array([[1, 2], [3, 4]])
arr_6 = np.array([[2, 4], [6, 9]])
print("arr_5\n", arr_5)
print("arr_6\n", arr_6)
np.remainder(arr_6, arr_5)


arr_5
 [[1 2]
 [3 4]]
arr_6
 [[2 4]
 [6 9]]


array([[0, 0],
       [0, 1]])

In [30]:
np.absolute([-1, -2])

array([1, 2])

In [31]:
np.power(arr_6, arr_5)

array([[   2,   16],
       [ 216, 6561]])

In [32]:
np.exp(arr_3)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [33]:
np.gcd.reduce([9, 12, 15])

3

In [34]:
np.lcm.reduce([9, 12, 15])

180

In [35]:
np.floor([1.2, 2.5])
np.ceil([1.2, 2.5])


array([2., 3.])

In [36]:
arr_7 = random.randint(100, size=(5, 3))
print("arr_7\n", arr_7)

arr_7
 [[91  7 53]
 [69 99 79]
 [80 58 62]
 [63 38 68]
 [15 60 78]]


In [37]:
mc_index = arr_7.argmax(axis=0)
mc_index

array([0, 1, 1], dtype=int64)

In [38]:
max_nums = arr_7[mc_index]
arr_7[mc_index, range(arr_7.shape[1])]

array([91, 99, 79])

In [39]:
print("arr_5\n", arr_5)
print("arr_6\n", arr_6)

arr_5
 [[1 2]
 [3 4]]
arr_6
 [[2 4]
 [6 9]]


In [40]:
np.dot(arr_5, arr_6)

array([[14, 22],
       [30, 48]])

In [41]:
arr_8 = np.array([[5, 6], [7, 8]])
arr_8

array([[5, 6],
       [7, 8]])

In [42]:
from numpy import linalg as LA
LA.multi_dot([arr_5, arr_6, arr_8])

array([[224, 260],
       [486, 564]])

In [43]:
np.inner(arr_5, arr_6)

array([[10, 24],
       [22, 54]])

In [44]:
arr_9 = np.array([[[1, 2],
        [3, 4]],
       [[5, 6],
        [7, 8]]])
arr_10 = np.array([[1, 2],
       [3, 4]], dtype=object)
np.tensordot(arr_9, arr_10)

array([30, 70], dtype=object)

In [45]:
import pandas
mydataset = {
 'cars': ["BMW", "Volvo", "Ford"],
 'passings': [3, 7, 2]
}
myvar = pandas.DataFrame(mydataset)
print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [46]:
import pandas
mydataset = {
 'cars': ["BMW", "Volvo", "Ford"],
 'passings': [3, 7, 2]
}
myvar = pandas.DataFrame(mydataset)
print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [47]:
import pandas as pd
a = [1, 7, 2]
myvar = pd.Series(a)
print(myvar)

0    1
1    7
2    2
dtype: int64


In [57]:
list1 = np.array([2,3,45,5],dtype=np.float32)
list1

array([ 2.,  3., 45.,  5.], dtype=float32)