In [1]:
import numpy as np
x = ["hello",1,"hi",2]
y = np.array(x,dtype=np.str_)
y


array(['hello', '1', 'hi', '2'], dtype='<U5')

In [67]:
m_list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9],[10,11,12]]
m_list_1

np_m_arr_1 = np.array(m_list_1)
print(len(np_m_arr_1))
print(type(np_m_arr_1))

4
<class 'numpy.ndarray'>


In [3]:
np.arange(1, 10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.zeros(4)

array([0., 0., 0., 0.])

In [5]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np_m_arr_1.size


12

In [7]:
from numpy import random

np.random.randint(10, 50, size=(2, 3))

array([[40, 36, 40],
       [29, 11, 43]])

In [8]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [10]:
np_m_arr_1.shape

(4, 3)

In [11]:
np.take(np_m_arr_1, [0, 3, 6,9])

array([ 1,  4,  7, 10])

In [12]:
np.put(np_m_arr_1, [0, 3, 6, 9], [10, 10, 10, 10])
print(np_m_arr_1)

[[10  2  3]
 [10  5  6]
 [10  8  9]
 [10 11 12]]


In [13]:
list_1 = [1, 2, 3, 4, 5]
np_arr_1 = np.array(list_1, dtype=np.int8)
np_arr_1

np_arr_1[:5:2]

array([1, 3, 5], dtype=int8)

In [14]:
np_m_arr_1[:,2]

array([ 3,  6,  9, 12])

In [15]:
np.unique(np_m_arr_1)

array([ 2,  3,  5,  6,  8,  9, 10, 11, 12])

In [16]:
np_m_arr_1.resize((3,4))
np_m_arr_1

array([[10,  2,  3, 10],
       [ 5,  6, 10,  8],
       [ 9, 10, 11, 12]])

In [17]:
np_m_arr_1.resize((3,4))
np_m_arr_1

array([[10,  2,  3, 10],
       [ 5,  6, 10,  8],
       [ 9, 10, 11, 12]])

In [18]:
np_m_arr_1.transpose()

array([[10,  5,  9],
       [ 2,  6, 10],
       [ 3, 10, 11],
       [10,  8, 12]])

In [19]:
np_m_arr_1.swapaxes(0,1)


array([[10,  5,  9],
       [ 2,  6, 10],
       [ 3, 10, 11],
       [10,  8, 12]])

In [20]:
np_m_arr_1.flatten('F')

array([10,  5,  9,  2,  6, 10,  3, 10, 11, 10,  8, 12])

In [21]:
np_m_arr_1.flatten()

array([10,  2,  3, 10,  5,  6, 10,  8,  9, 10, 11, 12])

In [22]:
arr_3 = np.array([1, 2, 3, 4])
arr_4 = np.array([2, 4, 6, 8])
arr_3 + arr_4

array([ 3,  6,  9, 12])

In [23]:
arr_5 = random.randint(100, size=(4))
arr_5

array([75, 98, 96, 91])

In [24]:
random.choice(arr_3)

2

In [25]:
arr_6 = random.randint(100, size=(2, 3))
arr_6


array([[76, 17, 65],
       [92, 40, 43]])

In [26]:
np.add(arr_3, arr_4)

array([ 3,  6,  9, 12])

In [27]:
arr_5 = np.array([[1, 2], [3, 4]])
arr_6 = np.array([[2, 4], [6, 9]])
print("arr_5\n", arr_5)
print("arr_6\n", arr_6)
np.remainder(arr_6, arr_5)


arr_5
 [[1 2]
 [3 4]]
arr_6
 [[2 4]
 [6 9]]


array([[0, 0],
       [0, 1]])

In [28]:
np.absolute([-1, -2])

array([1, 2])

In [29]:
np.power(arr_6, arr_5)

array([[   2,   16],
       [ 216, 6561]])

In [30]:
np.exp(arr_3)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [31]:
np.gcd.reduce([9, 12, 15])

3

In [32]:
np.lcm.reduce([9, 12, 15])

180

In [33]:
np.floor([1.2, 2.5])
np.ceil([1.2, 2.5])


array([2., 3.])

In [34]:
arr_7 = random.randint(100, size=(5, 3))
print("arr_7\n", arr_7)

arr_7
 [[65 19 22]
 [87 55 94]
 [53 76 61]
 [47 24 41]
 [87 60 66]]


In [35]:
mc_index = arr_7.argmax(axis=0)
mc_index

array([1, 2, 1], dtype=int64)

In [36]:
max_nums = arr_7[mc_index]
arr_7[mc_index, range(arr_7.shape[1])]

array([87, 76, 94])

In [37]:
print("arr_5\n", arr_5)
print("arr_6\n", arr_6)

arr_5
 [[1 2]
 [3 4]]
arr_6
 [[2 4]
 [6 9]]


In [38]:
np.dot(arr_5, arr_6)

array([[14, 22],
       [30, 48]])

In [39]:
arr_8 = np.array([[5, 6], [7, 8]])
arr_8

array([[5, 6],
       [7, 8]])

In [40]:
from numpy import linalg as LA
LA.multi_dot([arr_5, arr_6, arr_8])

array([[224, 260],
       [486, 564]])

In [41]:
np.inner(arr_5, arr_6)

array([[10, 24],
       [22, 54]])

In [42]:
arr_9 = np.array([[[1, 2],
        [3, 4]],
       [[5, 6],
        [7, 8]]])
arr_10 = np.array([[1, 2],
       [3, 4]], dtype=object)
np.tensordot(arr_9, arr_10)

array([30, 70], dtype=object)

In [43]:
import pandas
mydataset = {
 'cars': ["BMW", "Volvo", "Ford"],
 'passings': [3, 7, 2]
}
myvar = pandas.DataFrame(mydataset)
print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [44]:
import pandas
mydataset = {
 'cars': ["BMW", "Volvo", "Ford"],
 'passings': [3, 7, 2]
}
myvar = pandas.DataFrame(mydataset)
print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [45]:
import pandas as pd
a = [1, 7, 2]
myvar = pd.Series(a)
print(myvar)

0    1
1    7
2    2
dtype: int64


In [46]:
list1 = np.array([2,3,45,5],dtype=np.float32)
list1

array([ 2.,  3., 45.,  5.], dtype=float32)

In [47]:
list_1 = ['a', 'b', 'c', 'd']
labels = [1, 2, 3, 4]
ser_1 = pd.Series(data=list_1, index=labels)
ser_1


1    a
2    b
3    c
4    d
dtype: object

In [48]:
arr_1 = np.array([1, 2, 3, 4])
ser_2 = pd.Series(arr_1)
ser_2


0    1
1    2
2    3
3    4
dtype: int32

In [49]:
dict_1 = {"f_name": "Derek", 
              "l_name": "Banas", 
              "age": 44}
ser_3 = pd.Series(dict_1)
ser_3

f_name    Derek
l_name    Banas
age          44
dtype: object

In [50]:
ser_3["f_name"]

'Derek'

In [51]:
ser_2.dtype

dtype('int32')

In [52]:
ser_2 + ser_2

0    2
1    4
2    6
3    8
dtype: int32

In [53]:
np.exp(ser_2)

0     2.718282
1     7.389056
2    20.085537
3    54.598150
dtype: float64

In [54]:
ser_4 = pd.Series({4: 5, 5: 6, 6: 7, 7: 8})
ser_4

4    5
5    6
6    7
7    8
dtype: int64

In [55]:
ser_4 = pd.Series({8: 9, 9: 10}, name='rand_nums')
ser_4

8     9
9    10
Name: rand_nums, dtype: int64

In [56]:
arr_2 = np.random.randint(10, 50, size=(2, 3))
df_1 = pd.DataFrame(arr_2, ['A', 'B'], ['C', 'D', 'E'])
df_1

C   D   E
A  25  32  49
B  25  24  10

In [57]:
dict_3 = {'one': pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
         'two': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df_2 = pd.DataFrame(dict_3)
df_2

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

This out put is for tutorial purpose    

In [58]:
pd.DataFrame.from_dict(dict([('A', [1,2,3]), ('B', [4,5,6])]))

A  B
0  1  4
1  2  5
2  3  6

In [59]:
pd.DataFrame.from_dict(dict([('A', [1,2,3]), ('B', [4,5,6])]),
                      orient='index', columns=['one','two','three'])

one  two  three
A    1    2      3
B    4    5      6

In [60]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.linspace(0, 5, 7)


array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [62]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
len(np_m_arr_1)


4

In [70]:
np.random.randint(10, 50, 5)

array([48, 20, 38, 10, 25])

In [72]:
np_m_arr_1[0,1]

2

In [75]:
evens = np_m_arr_1[np_m_arr_1%2==0]
evens

array([ 2,  4,  6,  8, 10, 12])

In [77]:
np_m_arr_1[(np_m_arr_1 > 5) & (np_m_arr_1 < 9)]

array([6, 7, 8])

In [82]:
np_m_arr_1.reshape((2, 6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [83]:
np_m_arr_1.transpose()


array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [86]:

np_m_arr_1.flatten('F')

array([ 1,  4,  7, 10,  2,  5,  8, 11,  3,  6,  9, 12])

In [91]:
np_m_arr_1.sort(axis=0)
print(np_m_arr_1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
